# - Airflow Env variables.
substitutions:
  _GCP_PROJECT_ID: airflow-framework
  _PYTHON_VERSION: '3.8'
  _BUILD_IMG_NAME: airflow2_cicd:latest

steps:
# - Setup Python.
  # [START setup-python]
  - name: python
    entrypoint: pip
    args: ["install", "build", "wheel"]
    id: setup-python
  # [END setup-python]

# - Setup framework.
  # [START setup-framework]
  - name: python
    waitFor: ['setup-python']
    entrypoint: 'bash'
    args: 
      - '-c' 
      - |
        cd gcp-airflow-foundations 
        python3 setup.py sdist
    id: setup-framework
  # [END setup-framework]

# - Build a new Airflow2 image.
  # [START build-airflow2]
  - name: 'gcr.io/cloud-builders/docker'
    waitFor: ['setup-framework']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build -t gcr.io/${PROJECT_ID}/${_BUILD_IMG_NAME} \
        --build-arg PYTHON_VERSION=${_PYTHON_VERSION} \
        -f docker/Dockerfile .
    #env:
    #  - 'FOO=$_BAR'
    dir: '.'
    id: 'build-airflow2'
  # [END build-airflow2]

timeout: 3600s
images:
  - 'gcr.io/${PROJECT_ID}/${_BUILD_IMG_NAME}'