# - Airflow Env variables.
substitutions:
  _BUILD_IMG_NAME: airflow2_cicd_2:latest
  _PYTHON_VERSION: '3.8'
  _PROJECT_ID: airflow-framework
steps:
  # - Build a new Airflow2 image.
  # [START build-airflow2]
  - name: 'gcr.io/cloud-builders/docker'
    waitFor: ['-']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
          docker pull gcr.io/${PROJECT_ID}/${_BUILD_IMG_NAME} || exit 0
    id: 'pull-airflow2'
  - name: 'gcr.io/cloud-builders/docker'
    waitFor: ['-']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build -t gcr.io/${_PROJECT_ID}/${_BUILD_IMG_NAME} \
        --build-arg PYTHON_VERSION=${_PYTHON_VERSION} \
        --cache-from gcr.io/${PROJECT_ID}/${_BUILD_IMG_NAME} \
        -f docker/Dockerfile .
    dir: '.'
    id: 'build-airflow2'
  # [END build-airflow2]
  #


    #  - name: 'gcr.io/${PROJECT_ID}/${_COMPOSER_BUILD_IMG_NAME}'
#    waitFor: ['build-airflow2']
#    entrypoint: 'bash'
#    args:
#      - '-c'
#      - |
#          pytest tests/unit
#    id: "unit-test"

  # - Unit tests.
  # [START unit-test]

  - name: 'gcr.io/${_PROJECT_ID}/${_BUILD_IMG_NAME}'
    waitFor: ['build-airflow2']
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - 'whoami'
    id: "whoami"
  - name: 'gcr.io/${_PROJECT_ID}/${_BUILD_IMG_NAME}'
    waitFor: ['build-airflow2']
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - 'python -V'
    id: "python-versions"
  - name: 'gcr.io/${_PROJECT_ID}/${_BUILD_IMG_NAME}'
    waitFor: ['build-airflow2']
    entrypoint: '/bin/bash'
    args: ['-c', 'python', 'import sys; print(sys.path)']
    id: "python-list"
  - name: 'gcr.io/${_PROJECT_ID}/${_BUILD_IMG_NAME}'
    waitFor: ['build-airflow2']
    entrypoint: '/bin/bash'
    args: ['-c', 'pip install -r requirements.txt']
    id: "python-install"
#  - name: 'gcr.io/${_PROJECT_ID}/${_BUILD_IMG_NAME}'
#    waitFor: ['build-airflow2']
#    entrypoint: '/bin/bash'
#    args:
#      - '-c'
#      - 'cat docker/requirements-ci.txt'
#    id: "unit-test-3"
#  - name: 'gcr.io/${_PROJECT_ID}/${_BUILD_IMG_NAME}'
#    waitFor: ['build-airflow2']
#    entrypoint: '/bin/bash'
#    args:
#      - '-c'
#      - 'pip3 install --no-cache-dir -r docker/requirements-ci.txt'
#    id: "unit-test-2"
  - name: 'gcr.io/${_PROJECT_ID}/${_BUILD_IMG_NAME}'
    waitFor: ['build-airflow2']
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - 'pytest tests/unit -vv && py3clean .'
    id: "unit-test"
  # [END unit-test]

timeout: 1200s
images:
  - 'gcr.io/${PROJECT_ID}/${_BUILD_IMG_NAME}'
options:
  substitution_option: 'ALLOW_LOOSE'