---
source:
  name: "test_hds"
  source_type: GCS
  ingest_schedule: "@daily"
  start_date: "2021-08-30"
  acceptable_delay_minutes: 5
  extra_options:
    gcs_bucket: airflow-datasets-poc-v2
    gcs_objects: ["bigquery/hds_test_data_v2.csv"]
  gcp_project: sandbox-keyera-poc
  dataset_data_name: airflow_test
  connection: google_cloud_default
  notification_emails:
    - ''
  owner: owner
  version: 1
  landing_zone_options:
    landing_zone_dataset: airflow_landing
tables:
  - table_name: hds_test_snapshot
    hds_table_type: SNAPSHOT
    source_table_schema_object: gs://airflow-datasets-poc-v2/schema_hds.json
    surrogate_keys: ['customer_id','key']
    hds_metadata:
      eff_start_time_column_name: af_metadata_inserted_at
      hash_column_name: af_metadata_row_hash
    column_mapping: 
      customer_id: customerID
      key: key_id
      city: city_name