---
source:
  name: "test"
  source_type: GCS
  ingest_schedule: "@daily"
  start_date: "2021-08-30"
  acceptable_delay_minutes: 5
  extra_options:
    gcs_bucket: airflow-datasets-poc-v2
    gcs_objects: ["bigquery/hds_test_data.csv"]
  gcp_project: sandbox-keyera-poc
  dataset_data_name: airflow_test
  connection: google_cloud_default
  notification_emails:
    - ''
  owner: owner
  version: 1
  landing_zone_options:
    landing_zone_dataset: airflow_landing
tables:
  - table_name: test
    source_table_schema_object: gs://airflow-datasets-poc-v2/schema_hds.json
    surrogate_keys: ['customer_id','key']
    ods_config:
      ingestion_type: INCREMENTAL
      ods_metadata:
        hash_column_name: af_metadata_row_hash
        primary_key_hash_column_name: af_metadata_primary_key_hash
        ingestion_time_column_name: af_metadata_inserted_at
        update_time_column_name: af_metadata_updated_at
    hds_config:
      hds_table_type: SCD2
      hds_metadata:
        eff_start_time_column_name: af_metadata_created_at
        eff_end_time_column_name: af_metadata_expired_at
        hash_column_name: af_metadata_row_hash
    column_mapping: 
      customer_id: customerID
      key: key_id
      city: city_name