---
source:
  name: "twilio_text_messages"
  source_type: TWILIO
  ingest_schedule: "@daily"
  start_date: "2021-08-30"
  acceptable_delay_minutes: 5
  extra_options:
    gcs_bucket: airflow-datasets-poc
    twilio_account_sid: AC6e889487026563887777c14fdd2c4276
  gcp_project: sandbox-keyera-poc
  dataset_data_name: airflow_test
  connection: google_cloud_default
  notification_emails:
    - ''
  owner: owner
  version: 1
  landing_zone_options:
    landing_zone_dataset: airflow_landing
tables:
  - table_name: text_messages
    landing_zone_table_name_override: twilio_text_messages
    ingestion_type: INCREMENTAL
    surrogate_keys: ['sid']
    update_columns: []
    ods_metadata:
      hash_column_name: af_metadata_row_hash
      primary_key_hash_column_name: af_metadata_primary_key_hash
      ingestion_time_column_name: af_metadata_inserted_at
      update_time_column_name: af_metadata_updated_at