source:
  name: SampleGCS
  source_type: GCS
  ingest_schedule: "@daily"
  start_date: "2022-01-03"
  acceptable_delay_minutes: 5
  extra_options:
    gcs_bucket: public-gcp-airflow-foundation-samples
    gcs_source_config:
      templated_file_name: "{{ TABLE_NAME }}"
      source_format: CSV
      delimeter: ","
      file_prefix_filtering: False
  gcp_project: airflow-framework
  location: us-central1
  dataset_data_name: af_test_ods
  dataset_hds_override: af_test_hds
  owner: test_user
  notification_emails: []
  landing_zone_options:
    landing_zone_dataset: af_test_hds_landing_zone
  schema_options:
    schema_source_type: AUTO
    version: 1
tables:
  - table_name: users
    ingestion_type: FULL
    surrogate_keys: []
    extra_options:
      gcs_table_config:
        directory_prefix: "toedh/PROD/WA/"
        allow_quoted_newlines: True

