---
source:
  name: "test csv file"
  source_type: GCS
  ingest_schedule: "@daily"
  start_date: "2021-08-24"
  acceptable_delay_minutes: 5
  extra_options:
    #uri: ["gs://airflow-datasets-poc/bigquery/raw_measurements.csv"]
    # Need to provide support for extracting entire directory content: gs:/folder/*
    gcs_bucket: airflow-datasets-poc
    gcs_objects: ["bigquery/raw_measurements.csv"]
  gcp_project: badal-sandbox-309813
  dataset_data_name: airflow_test
  dataset_tmp_name: airflow_test
  connection: google_cloud_default
  notification_emails:
    - michail@badal.io
    #- daniel.kulikov@cogeco.com
  owner: owner
  version: 1
tables:
  - table_name: raw_measurements
    #write_mode: UPSERT
    #ods_add_cdc_fields: true
    #surrogate_keys: []
    #update_columns: []
    #object_prefix: none
    #transformations: []
    sink_table_name : gcs_to_bq_table # Output table name in BQ